# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `authtrail` gem.
# Please instead update this file by running `bin/tapioca gem authtrail`.

# source://authtrail//lib/auth_trail/manager.rb#1
module AuthTrail
  class << self
    # Returns the value of attribute exclude_method.
    #
    # source://authtrail//lib/authtrail.rb#12
    def exclude_method; end

    # Sets the attribute exclude_method
    #
    # @param value the value to set the attribute exclude_method to.
    #
    # source://authtrail//lib/authtrail.rb#12
    def exclude_method=(_arg0); end

    # Returns the value of attribute geocode.
    #
    # source://authtrail//lib/authtrail.rb#12
    def geocode; end

    # Sets the attribute geocode
    #
    # @param value the value to set the attribute geocode to.
    #
    # source://authtrail//lib/authtrail.rb#12
    def geocode=(_arg0); end

    # Returns the value of attribute identity_method.
    #
    # source://authtrail//lib/authtrail.rb#12
    def identity_method; end

    # Sets the attribute identity_method
    #
    # @param value the value to set the attribute identity_method to.
    #
    # source://authtrail//lib/authtrail.rb#12
    def identity_method=(_arg0); end

    # Returns the value of attribute job_queue.
    #
    # source://authtrail//lib/authtrail.rb#12
    def job_queue; end

    # Sets the attribute job_queue
    #
    # @param value the value to set the attribute job_queue to.
    #
    # source://authtrail//lib/authtrail.rb#12
    def job_queue=(_arg0); end

    # source://authtrail//lib/authtrail.rb#62
    def safely(default: T.unsafe(nil)); end

    # source://authtrail//lib/authtrail.rb#24
    def track(strategy:, scope:, identity:, success:, request:, user: T.unsafe(nil), failure_reason: T.unsafe(nil)); end

    # Returns the value of attribute track_method.
    #
    # source://authtrail//lib/authtrail.rb#12
    def track_method; end

    # Sets the attribute track_method
    #
    # @param value the value to set the attribute track_method to.
    #
    # source://authtrail//lib/authtrail.rb#12
    def track_method=(_arg0); end

    # Returns the value of attribute transform_method.
    #
    # source://authtrail//lib/authtrail.rb#12
    def transform_method; end

    # Sets the attribute transform_method
    #
    # @param value the value to set the attribute transform_method to.
    #
    # source://authtrail//lib/authtrail.rb#12
    def transform_method=(_arg0); end
  end
end

# source://authtrail//lib/auth_trail/geocode_job.rb#2
class AuthTrail::GeocodeJob < ::ActiveJob::Base
  # source://authtrail//lib/auth_trail/geocode_job.rb#7
  def perform(login_activity); end

  class << self
    # source://activejob/7.1.3.2/lib/active_job/queue_name.rb#55
    def queue_name; end
  end
end

# source://authtrail//lib/auth_trail/manager.rb#2
module AuthTrail::Manager
  class << self
    # source://authtrail//lib/auth_trail/manager.rb#4
    def after_set_user(user, auth, opts); end

    # source://authtrail//lib/auth_trail/manager.rb#17
    def before_failure(env, opts); end

    private

    # source://authtrail//lib/auth_trail/manager.rb#32
    def detect_strategy(auth); end
  end
end

# source://authtrail//lib/auth_trail/version.rb#2
AuthTrail::VERSION = T.let(T.unsafe(nil), String)
