# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rice` gem.
# Please instead update this file by running `bin/tapioca gem rice`.

module Rice; end
module Rice::Std; end

class Rice::Std::Vector__double_allocator__double____
  include ::Enumerable

  def initialize(*_arg0); end

  def <<(*_arg0); end
  def [](*_arg0); end
  def []=(*_arg0); end
  def append(*_arg0); end
  def at(*_arg0); end
  def capacity(*_arg0); end
  def clear(*_arg0); end
  def copy(*_arg0); end
  def count(*_arg0); end
  def delete(*_arg0); end
  def delete_at(*_arg0); end
  def each; end
  def empty?(*_arg0); end
  def first(*_arg0); end
  def include?(*_arg0); end
  def index(*_arg0); end
  def insert(*_arg0); end
  def last(*_arg0); end
  def length(*_arg0); end
  def max_size(*_arg0); end
  def pop(*_arg0); end
  def push(*_arg0); end
  def reserve(*_arg0); end
  def resize(*_arg0); end
  def shrink_to_fit(*_arg0); end
  def size(*_arg0); end
  def to_a(*_arg0); end
  def to_s(*_arg0); end
end
