# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `simplecov-tailwindcss` gem.
# Please instead update this file by running `bin/tapioca gem simplecov-tailwindcss`.

# source://simplecov-tailwindcss//lib/simplecov-tailwindcss.rb#15
module SimpleCov
  class << self
    # source://simplecov/0.22.0/lib/simplecov.rb#174
    def at_exit_behavior; end

    # source://simplecov/0.22.0/lib/simplecov.rb#170
    def clear_result; end

    # source://simplecov/0.22.0/lib/simplecov.rb#86
    def collate(result_filenames, profile = T.unsafe(nil), ignore_timeout: T.unsafe(nil), &block); end

    # source://simplecov/0.22.0/lib/simplecov.rb#223
    def exit_and_report_previous_error(exit_status); end

    # source://simplecov/0.22.0/lib/simplecov.rb#200
    def exit_status_from_exception; end

    # source://simplecov/0.22.0/lib/simplecov.rb#28
    def external_at_exit; end

    # source://simplecov/0.22.0/lib/simplecov.rb#28
    def external_at_exit=(_arg0); end

    # source://simplecov/0.22.0/lib/simplecov.rb#28
    def external_at_exit?; end

    # source://simplecov/0.22.0/lib/simplecov.rb#131
    def filtered(files); end

    # source://simplecov/0.22.0/lib/simplecov.rb#268
    def final_result_process?; end

    # source://simplecov/0.22.0/lib/simplecov.rb#142
    def grouped(files); end

    # source://simplecov/0.22.0/lib/simplecov.rb#162
    def load_adapter(name); end

    # source://simplecov/0.22.0/lib/simplecov.rb#158
    def load_profile(name); end

    # source://simplecov/0.22.0/lib/simplecov.rb#24
    def pid; end

    # source://simplecov/0.22.0/lib/simplecov.rb#24
    def pid=(_arg0); end

    # source://simplecov/0.22.0/lib/simplecov.rb#213
    def previous_error?(error_exit_status); end

    # source://simplecov/0.22.0/lib/simplecov.rb#248
    def process_result(result); end

    # source://simplecov/0.22.0/lib/simplecov.rb#233
    def process_results_and_report_error; end

    # source://simplecov/0.22.0/lib/simplecov.rb#229
    def ready_to_process_results?; end

    # source://simplecov/0.22.0/lib/simplecov.rb#101
    def result; end

    # source://simplecov/0.22.0/lib/simplecov.rb#124
    def result?; end

    # source://simplecov/0.22.0/lib/simplecov.rb#256
    def result_exit_status(result); end

    # source://simplecov/0.22.0/lib/simplecov.rb#296
    def round_coverage(coverage); end

    # source://simplecov/0.22.0/lib/simplecov.rb#186
    def run_exit_tasks!; end

    # source://simplecov/0.22.0/lib/simplecov.rb#24
    def running; end

    # source://simplecov/0.22.0/lib/simplecov.rb#24
    def running=(_arg0); end

    # source://simplecov/0.22.0/lib/simplecov.rb#48
    def start(profile = T.unsafe(nil), &block); end

    # source://simplecov/0.22.0/lib/simplecov.rb#276
    def wait_for_other_processes; end

    # source://simplecov/0.22.0/lib/simplecov.rb#285
    def write_last_run(result); end

    private

    # source://simplecov/0.22.0/lib/simplecov.rb#399
    def adapt_coverage_result; end

    # source://simplecov/0.22.0/lib/simplecov.rb#371
    def add_not_loaded_files(result); end

    # source://simplecov/0.22.0/lib/simplecov.rb#302
    def initial_setup(profile, &block); end

    # source://simplecov/0.22.0/lib/simplecov.rb#363
    def lookup_corresponding_ruby_coverage_name(criterion); end

    # source://simplecov/0.22.0/lib/simplecov.rb#425
    def make_parallel_tests_available; end

    # source://simplecov/0.22.0/lib/simplecov.rb#434
    def probably_running_parallel_tests?; end

    # source://simplecov/0.22.0/lib/simplecov.rb#388
    def process_coverage_result; end

    # source://simplecov/0.22.0/lib/simplecov.rb#410
    def remove_useless_results; end

    # source://simplecov/0.22.0/lib/simplecov.rb#420
    def result_with_not_loaded_files; end

    # source://simplecov/0.22.0/lib/simplecov.rb#314
    def start_coverage_measurement; end

    # source://simplecov/0.22.0/lib/simplecov.rb#349
    def start_coverage_with_criteria; end
  end
end

# source://simplecov-tailwindcss//lib/simplecov-tailwindcss.rb#16
module SimpleCov::Formatter
  class << self
    # source://simplecov/0.22.0/lib/simplecov/default_formatter.rb#7
    def from_env(env); end
  end
end

# source://simplecov-tailwindcss//lib/simplecov-tailwindcss.rb#17
class SimpleCov::Formatter::TailwindFormatter
  # @return [TailwindFormatter] a new instance of TailwindFormatter
  #
  # source://simplecov-tailwindcss//lib/simplecov-tailwindcss.rb#18
  def initialize; end

  # @return [Boolean]
  #
  # source://simplecov-tailwindcss//lib/simplecov-tailwindcss.rb#39
  def branchable_result?; end

  # source://simplecov-tailwindcss//lib/simplecov-tailwindcss.rb#22
  def format(result); end

  # @return [Boolean]
  #
  # source://simplecov-tailwindcss//lib/simplecov-tailwindcss.rb#43
  def line_status?(source_file, line); end

  # source://simplecov-tailwindcss//lib/simplecov-tailwindcss.rb#33
  def output_message(result); end

  private

  # source://simplecov-tailwindcss//lib/simplecov-tailwindcss.rb#66
  def asset_output_path; end

  # source://simplecov-tailwindcss//lib/simplecov-tailwindcss.rb#79
  def assets_path(name); end

  # source://simplecov-tailwindcss//lib/simplecov-tailwindcss.rb#174
  def branch_enabled_class; end

  # source://simplecov-tailwindcss//lib/simplecov-tailwindcss.rb#165
  def code_coverage_class(status); end

  # source://simplecov-tailwindcss//lib/simplecov-tailwindcss.rb#132
  def coverage_badge_class(covered_percent); end

  # source://simplecov-tailwindcss//lib/simplecov-tailwindcss.rb#122
  def coverage_class(covered_percent); end

  # source://simplecov-tailwindcss//lib/simplecov-tailwindcss.rb#115
  def format_number(number); end

  # source://simplecov-tailwindcss//lib/simplecov-tailwindcss.rb#87
  def generate_dialog(file); end

  # source://simplecov-tailwindcss//lib/simplecov-tailwindcss.rb#99
  def generate_file_detail(file); end

  # source://simplecov-tailwindcss//lib/simplecov-tailwindcss.rb#104
  def generate_group_page(title, files, created_date); end

  # source://simplecov-tailwindcss//lib/simplecov-tailwindcss.rb#95
  def generate_stat_card(title, stat, color); end

  # source://simplecov-tailwindcss//lib/simplecov-tailwindcss.rb#190
  def hide_show(title); end

  # source://simplecov-tailwindcss//lib/simplecov-tailwindcss.rb#182
  def id(source_file); end

  # source://simplecov-tailwindcss//lib/simplecov-tailwindcss.rb#152
  def line_coverage_class(status); end

  # source://simplecov-tailwindcss//lib/simplecov-tailwindcss.rb#62
  def output_path; end

  # source://simplecov-tailwindcss//lib/simplecov-tailwindcss.rb#110
  def remove_spaces(name); end

  # source://simplecov-tailwindcss//lib/simplecov-tailwindcss.rb#186
  def shortened_filename(file); end

  # source://simplecov-tailwindcss//lib/simplecov-tailwindcss.rb#142
  def strength_class(covered_strength); end

  # source://simplecov-tailwindcss//lib/simplecov-tailwindcss.rb#54
  def template(name); end
end

# source://simplecov-tailwindcss//lib/simplecov-tailwindcss/version.rb#6
SimpleCov::Formatter::TailwindFormatter::VERSION = T.let(T.unsafe(nil), String)
