version: "3.2"

services:
  db:
    image: postgres:16-alpine
    user: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7.2.4-alpine
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - redis:/var/lib/redis/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  web:
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    build: .
    volumes:
      - .:/project
      - type: tmpfs
        target: /project/tmp/pids/
    ports:
      - 3000:3000
    environment:
      - RUBY_YJIT_ENABLE=1
      - APP_URL=http://localhost:3000
      - ASSET_HOST=http://localhost:3000
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - PORT=3000
      - RAILS_ENV=development
      - RAILS_LOG_TO_STDOUT=true
      - REDIS_URL=redis://redis:6379/0
      - LAUNCHY_DRY_RUN=true
      - BROWSER=/dev/null
  worker:
    depends_on:
      - web
    build: .
    volumes:
      - .:/project
      - type: tmpfs
        target: /project/tmp/pids/
    command: bundle exec sidekiq -c 2
    ports:
      - 7433:7433
    environment:
      - RUBY_YJIT_ENABLE=1
      - HOSTNAME=sidekiq_alive
      - PORT=7433
      - APP_URL=http://localhost:3000
      - ASSET_HOST=http://localhost:3000
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - PORT=3000
      - RAILS_ENV=development
      - RAILS_LOG_TO_STDOUT=true
      - REDIS_URL=redis://redis:6379/0
      - LAUNCHY_DRY_RUN=true
      - BROWSER=/dev/null
volumes:
  postgres:
  redis:
