# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ApplicationViewComponent`.
# Please instead update this file by running `bin/tapioca dsl ApplicationViewComponent`.

class ApplicationViewComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
